# Setup
title:               'Reindeer Note'
tagline:             'Keep learning, growing & enjoying!'
description:         '期許自己能從程式麻瓜成長為可以創造實用工具'
url:                 https://lindawu100.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Linda
  url:               https://twitter.com/Lindawu100
  email:             pinky510100@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

social:
  - name: Twitter
    icon: twitter
    username: lindawu100
    url: https://twitter.com/Lindawu100
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: lindawu100
    url: https://github.com/lindawu100
    desc: Fork me on GitHub
    share: false
